repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        files: ^(tursi/|tests/).*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^(tursi/|tests/).*\.py$
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: local
    hooks:
      - id: verify-changelog
        name: Verify CHANGELOG.md updates
        entry: python scripts/verify_changelog.py
        language: python
        additional_dependencies: ['tomli']
        files: ^(CHANGELOG\.md|pyproject\.toml)$
        pass_filenames: false
