name: 'Setup Poetry'
description: 'Sets up Python and Poetry with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.11'
  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: '1.7.1'
  install-root:
    description: 'Whether to install the root package'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ hashFiles('**/poetry.lock') }}

    - name: Update lock file
      shell: bash
      run: poetry lock --no-update

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction --no-root

    - name: Install project
      if: inputs.install-root == 'true'
      shell: bash
      run: poetry install --no-interaction
