name: Update Changelog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'docs: update changelog')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
          pip install python-semantic-release
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Generate Changelog
        run: |
          # Generate changelog
          semantic-release changelog --unreleased > new_changes.md
          
          # Update CHANGELOG.md
          if [ -f CHANGELOG.md ]; then
            cat new_changes.md CHANGELOG.md > temp_changelog.md
            mv temp_changelog.md CHANGELOG.md
          else
            mv new_changes.md CHANGELOG.md
          fi
          
          # Check if there are any changes
          if git diff --quiet CHANGELOG.md; then
            echo "No changes to CHANGELOG.md"
          else
            # Show the changes
            git diff CHANGELOG.md
            
            # Commit changes
            git add CHANGELOG.md
            git commit -m "docs: update changelog"
            git push origin HEAD:main
          fi 