name: Lint

on:
  push:
    branches: [ "main", "release/*" ]
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:
    branches: [ "main", "release/*" ]
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Poetry
        uses: ./.github/workflows/action.yml
        with:
          python-version: "3.11"
          poetry-version: "1.7.1"
          install-root: false

      - name: Run black
        run: poetry run black --check tursi tests

      - name: Run flake8
        run: poetry run flake8 tursi tests

      - name: Run mypy
        run: poetry run mypy tursi tests
