name: Lint

on:
  push:
    branches: [ main, 'release/*' ]
    paths:
      - '**.py'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry
        uses: ./.github/workflows/poetry-setup
        with:
          python-version: '3.11'
          poetry-version: '1.7.1'
          install-root: true

      - name: Run black
        run: poetry run black --check tursi tests

      - name: Run flake8
        run: poetry run flake8 tursi tests

      - name: Run mypy
        run: poetry run mypy tursi tests
