name: Release

on:
  push:
    tags:
      - 'release/v*'  # Breaking changes, major, and security updates
      - 'patch/v*'    # Minor and regular patch updates

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Clear cache (force fresh installation)
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/*/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building release for version $VERSION"

      - name: Update pyproject.toml version
        run: |
          # Install required tools
          pip install tomli tomli-w
          
          # Update version in pyproject.toml
          python -c "
          import tomli
          import tomli_w
          
          with open('pyproject.toml', 'rb') as f:
              config = tomli.load(f)
          
          config['tool']['poetry']['version'] = '${{ steps.get_version.outputs.version }}'
          
          with open('pyproject.toml', 'wb') as f:
              tomli_w.dump(config, f)
          "
          
          # Verify the change
          cat pyproject.toml | grep version

      - name: Install dependencies
        run: |
          poetry install --no-interaction
          poetry run pip install twine

      - name: Build package
        run: |
          # Show Python version and environment info
          poetry run python --version
          poetry run pip list
          
          # Show current directory structure
          echo "Current directory structure:"
          ls -R
          
          # Show package contents
          echo "Package contents:"
          cat tursi/__init__.py
          echo "---"
          cat tursi/engine.py
          
          # Build the package with verbose output
          poetry build -vvv
          
          # Verify the built files
          echo "Built files:"
          ls -l dist/
          poetry run twine check dist/*
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: Release v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true 