name: Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          pip install conventional-changelog-cli
          
      - name: Generate Release Notes
        run: |
          # Get the version from the tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building release for version $VERSION"
          
          # Ensure CHANGELOG.md exists
          touch CHANGELOG.md
          # Generate changelog for the release
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          
      - name: Build package
        run: |
          # Show Python version and environment info
          python --version
          pip list
          
          # Build the package
          python -m build
          
          # List the built files
          ls -l dist/
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          generate_release_notes: true
          
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true 