name: Release

on:
  push:
    tags:
      - 'release/v*'  # Only trigger on significant updates

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools twine
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/release/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building release for version $VERSION"
          
      - name: Build package
        run: |
          # Show Python version and environment info
          python --version
          pip list
          
          # Build the package
          python -m build
          
          # Verify the built files
          ls -l dist/
          twine check dist/*
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true 