name: Test

on:
  push:
    branches: [ "main", "release/*" ]
    paths:
      - 'tursi/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tursi/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Poetry
      uses: ./.github/workflows
      with:
        python-version: '3.11'
        poetry-version: '1.7.1'
        install-root: true

    - name: Run tests
      run: poetry run pytest tests/ -v
