name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest tests/
          
      - name: Run linting
        run: |
          flake8 tursi
          
      - name: Build package
        run: |
          python -m build
          
      - name: Install package
        run: |
          pip install dist/*.whl
          
      - name: Test installed package
        run: |
          tursi-engine --help
          tursi-test --help 