name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest tests/
          
      - name: Run linting
        run: |
          flake8 tursi
          
      - name: Build package
        run: |
          python -m build
          
      - name: Install package
        run: |
          pip install dist/*.whl
          
      - name: Test installed package
        run: |
          tursi-engine --help
          tursi-test --help

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python" 